version: "3.7"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: AcmeFileUpload.API/.
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 5001:5001
    volumes:
    - "./uploads:/app/uploads:rw"
  web:
    build:
      dockerfile: Dockerfile
      context: AcmeFileUpload.Web/.
    ports:
      - 5000:80